import { useEffect, useState } from 'react';

async function api(path, options = {}) {
  const token = localStorage.getItem('lw_token');
  const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token && { Authorization: `Bearer ${token}` }), ...options.headers } });
  const raw = await response.text();
  let data = {};
  try { data = raw ? JSON.parse(raw) : {}; } catch { data = {}; }
  if (!response.ok) throw new Error(data.message || 'Something went wrong.');
  return data;
}

const demoStudents = [
  {id:101,fullName:'Amara Okafor',email:'amara@example.com',phone:'+234 800 000 0001',experienceLevel:'Beginner',learningGoal:'Build cloud deployment and automation skills.',status:'pending'},
  {id:102,fullName:'Daniel Adeyemi',email:'daniel@example.com',phone:'+234 800 000 0002',experienceLevel:'Intermediate',learningGoal:'Move into a DevOps engineering role.',status:'pending'},
  {id:103,fullName:'Zainab Bello',email:'zainab@example.com',phone:'+234 800 000 0003',experienceLevel:'Beginner',learningGoal:'Learn Linux, AWS and CI/CD through practical projects.',status:'approved'},
];

const Logo = () => <a className="brand" href="#home"><img src="/livingworth-logo.jpeg" alt="Livingworth Academy" /></a>;

function Header({ navigate }) {
  return <header className="nav"><Logo/><nav><a href="#curriculum">Curriculum</a><a href="#experience">How it works</a><a href="#schedule">Schedule</a><a href="#projects">Projects</a></nav><div className="nav-actions"><button className="text-btn" onClick={()=>navigate('student-login')}>Student login</button><button className="button primary" onClick={()=>navigate('register')}>Apply now</button></div></header>;
}

function Home({ navigate }) {
  const modules = [
    ['01','DevOps & SDLC','Understand DevOps culture, software delivery, Agile, Scrum, HLD vs LLD, Jira workflows, stories and epics.'],
    ['02','Linux & Shell','Work confidently in Linux, manage files and permissions, troubleshoot services and automate tasks with Bash.'],
    ['03','Git & GitHub','Use professional branching, commits, pull requests, code reviews and collaborative source-control workflows.'],
    ['04','AWS & Cloud','Launch EC2 instances, configure networking and security, use AWS CLI and deploy applications to the cloud.'],
    ['05','Ansible & Terraform','Automate configuration with playbooks and build repeatable cloud infrastructure using Infrastructure as Code.'],
    ['06','Docker & Containers','Build images, run containers, manage volumes and networks, and Dockerize real frontend and backend applications.'],
    ['07','Kubernetes','Deploy scalable workloads with Pods, Deployments, Services, ConfigMaps, Secrets and Ingress.'],
    ['08','CI/CD & Observability','Create Jenkins and GitHub Actions pipelines; monitor systems with Prometheus and Grafana.'],
  ];
  const projects = [
    ['Cloud foundation','Launch and secure an AWS EC2 Linux server, then document the environment.'],
    ['Automation','Write shell scripts, an Ansible playbook and Terraform configuration for repeatable infrastructure.'],
    ['Container delivery','Dockerize a full-stack application and publish the images through a clean GitHub workflow.'],
    ['Kubernetes platform','Deploy an application with Services and Ingress, then capture monitoring evidence.'],
    ['End-to-end capstone','Build a complete CI/CD path from Git commit to cloud deployment, monitoring and project presentation.'],
  ];
  return <><Header navigate={navigate}/><main>
    <section className="hero" id="home"><div><p className="eyebrow">12-week DevOps engineering bootcamp</p><h1>Learn DevOps.<br/><em>Build for real.</em></h1><p className="lead">Move from beginner to confident practitioner through live classes, guided troubleshooting, practical labs, project reviews and an end-to-end final project.</p><div className="actions"><button className="button gold" onClick={()=>navigate('register')}>Apply for the next cohort</button><a className="button light" href="#curriculum">View curriculum</a></div><div className="trust"><span>✓ 54-class-day roadmap</span><span>✓ Live on Google Meet</span><span>✓ Portfolio-ready projects</span></div></div><div className="hero-art"><div className="orbit o1">&lt;/&gt;</div><div className="orbit o2">☁</div><div className="orbit o3">∞</div><div className="core">DEV<span>OPS</span></div></div></section>
    <section className="devops-strip"><span>LINUX</span><span>GIT</span><span>AWS</span><span>ANSIBLE</span><span>TERRAFORM</span><span>DOCKER</span><span>KUBERNETES</span><span>JENKINS</span><span>GRAFANA</span></section>
    <section className="visual-feature"><div><p className="eyebrow">From code to production</p><h2>See the complete delivery system—not isolated tools.</h2><p>Learn how source control, automation, containers, orchestration, pipelines, cloud infrastructure and monitoring work together in a real DevOps environment.</p></div><img src="/devops-delivery-workflow.jpg" alt="Visual representation of a DevOps delivery workflow from source code through cloud deployment and monitoring" /></section>
    <section className="intro" id="experience"><p className="eyebrow">The Livingworth approach</p><h2>Watch it. Understand it.<br/>Build it yourself.</h2><p>Pre-recorded lessons introduce each concept. Live sessions focus on clear explanations, practical demonstrations, questions, troubleshooting and the kind of mistakes engineers meet in real environments.</p><div className="experience-grid"><article><b>01</b><h3>Prepare</h3><p>Watch the lesson and review the class objectives before the live session.</p></article><article><b>02</b><h3>Practise live</h3><p>Follow demonstrations, ask questions and troubleshoot alongside your instructor.</p></article><article><b>03</b><h3>Prove the skill</h3><p>Complete assignments, maintain GitHub evidence and receive project feedback.</p></article></div></section>
    <section className="curriculum" id="curriculum"><div className="section-head"><div><p className="eyebrow">Beginner to intermediate</p><h2>Your DevOps roadmap</h2></div><p className="section-copy">A deliberate progression from delivery fundamentals to cloud automation, containers, orchestration, pipelines and observability.</p></div><div className="module-grid">{modules.map(m=><article key={m[0]}><b>{m[0]}</b><div><h3>{m[1]}</h3><p>{m[2]}</p></div></article>)}</div></section>
    <section className="schedule" id="schedule"><div><p className="eyebrow">Cohort rhythm</p><h2>Three focused touchpoints every week.</h2><p>Classes run on Google Meet from 8:00–9:00 p.m. GMT+1. Every week combines orientation, review and a deeper practical session.</p><ul><li>Laptop: 8GB RAM minimum, 16GB preferred</li><li>Reliable internet, Gmail and GitHub account</li><li>VS Code, Git, Docker, terminal/WSL or Linux VM</li><li>AWS free-tier and Docker Hub accounts</li></ul></div><div className="week"><article><b>MON</b><h3>Orientation</h3><p>New topic, learning objectives and guided foundation.</p></article><article><b>WED</b><h3>Summary & practice</h3><p>Review, questions, demonstrations and troubleshooting.</p></article><article><b>FRI</b><h3>Live class</h3><p>Deep practical teaching, discussion and project work.</p></article></div></section>
    <section className="mentor"><img src="/devops-mentor-lab.jpg" alt="DevOps mentor guiding learners during a practical technology session"/><div><p className="eyebrow">Meet your mentor</p><h2>Guidance grounded in real DevOps work.</h2><span className="mentor-name">Jethro Femi</span><span className="mentor-role">Lead DevOps Mentor · Managing Director</span><p>The programme is led with practical engineering experience, simple explanations and live troubleshooting. Students learn not only which commands to run, but how to reason through failures, communicate technical decisions and deliver reliable systems.</p><div className="mentor-points"><span>Cloud & infrastructure</span><span>CI/CD & automation</span><span>Containers & orchestration</span><span>Production troubleshooting</span></div></div></section>
    <section className="projects" id="projects"><p className="eyebrow">Evidence, not just theory</p><h2>Projects you can explain, defend and demonstrate.</h2><div className="project-list">{projects.map((p,i)=><article key={p[0]}><span>0{i+1}</span><div><h3>{p[0]}</h3><p>{p[1]}</p></div></article>)}</div></section>
    <section className="expectations"><div><p className="eyebrow">Built for committed learners</p><h2>What success requires</h2></div><div className="expectation-grid"><p><b>Show up.</b> Attendance, punctuality and active participation are essential.</p><p><b>Practise outside class.</b> DevOps becomes real through repetition and independent troubleshooting.</p><p><b>Submit your work.</b> Assignments, GitHub evidence and the final project are part of completion.</p><p><b>Stay accountable.</b> Learners missing more than half of the programme may be removed.</p></div></section>
    <section className="career"><p className="eyebrow">Beyond the tools</p><h2>Finish ready to tell your engineering story.</h2><p>The final phase covers networking, project presentation, GitHub portfolio improvement, interview preparation and explaining technical decisions with confidence.</p><button className="button gold" onClick={()=>navigate('register')}>Start your application</button></section>
    <section className="cta"><Logo/><h2>Build your DevOps future.</h2><p>Join a practical academy where every concept leads to something you can create.</p><button className="button gold" onClick={()=>navigate('register')}>Apply to Livingworth Academy</button></section>
  </main><footer className="footer"><Logo/><div><a href="#curriculum">Curriculum</a><button onClick={()=>navigate('student-login')}>Student portal</button><button onClick={()=>navigate('admin-login')}>Admin portal</button></div><p>© {new Date().getFullYear()} Livingworth Academy.</p></footer></>;
}

function AuthLayout({title,subtitle,children,navigate}) {
  return <main className="auth-page"><section className="auth-brand"><Logo/><div><p className="eyebrow">Livingworth Academy Portal</p><h1>Learn with purpose.<br/><em>Grow with confidence.</em></h1></div><button className="back" onClick={()=>navigate('home')}>← Return to website</button></section><section className="auth-panel"><div className="auth-box"><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></main>;
}

function Login({portal,navigate,onLogin}) {
  const [message,setMessage]=useState('');
  function openOfflineDemo(){const user={id:'demo-admin',fullName:'Livingworth Administrator',email:'admin@livingworthacademy.com',role:'admin',status:'approved',demo:true};localStorage.setItem('lw_demo_admin','true');onLogin(user)}
  async function submit(e){e.preventDefault();setMessage('Signing in…');try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),portal})});localStorage.setItem('lw_token',data.token);onLogin(data.user)}catch(err){setMessage(`${err.message} ${portal==='admin'?'You can still open the offline admin preview below.':''}`)}}
  return <AuthLayout navigate={navigate} title={portal==='admin'?'Administrator login':'Welcome back'} subtitle={portal==='admin'?'Manage student applications and academy access.':'Continue your Livingworth learning journey.'}><form className="form" onSubmit={submit}><label>Email address<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button className="button primary full">Sign in</button><p className="form-message">{message}</p></form>{portal==='admin'&&<div className="offline-box"><b>Backend unavailable?</b><p>Open a browser-only preview of the admin portal. Demo approvals stay on this device and do not change the real database.</p><button className="button offline full" onClick={openOfflineDemo}>Open offline admin preview</button></div>}<div className="switch">{portal==='admin'?<>Student? <button onClick={()=>navigate('student-login')}>Student login</button></>:<>New student? <button onClick={()=>navigate('register')}>Register here</button><br/><button className="admin-link" onClick={()=>navigate('admin-login')}>Administrator login</button></>}</div></AuthLayout>;
}

function Register({navigate}) {
  const [message,setMessage]=useState(''); const [done,setDone]=useState(false);
  async function submit(e){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(values.password!==values.confirmPassword){setMessage('Passwords do not match.');return}setMessage('Submitting…');try{const data=await api('/auth/register',{method:'POST',body:JSON.stringify(values)});setMessage(data.message);setDone(true);e.currentTarget.reset()}catch(err){setMessage(err.message)}}
  return <AuthLayout navigate={navigate} title="Student registration" subtitle="Apply for an account. An administrator will review your registration before you can log in."><form className="form two" onSubmit={submit}><label>Full name<input name="fullName" required /></label><label>Email address<input name="email" type="email" required /></label><label>Phone number<input name="phone" /></label><label>Experience level<select name="experienceLevel"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label className="wide">What do you want to achieve?<textarea name="learningGoal" rows="3" required /></label><label>Password<input name="password" type="password" minLength="8" required /></label><label>Confirm password<input name="confirmPassword" type="password" minLength="8" required /></label><button className="button primary full wide" disabled={done}>{done?'Application submitted':'Submit application'}</button><p className={`form-message wide ${done?'success':''}`}>{message}</p></form><p className="switch">Already registered? <button onClick={()=>navigate('student-login')}>Sign in</button></p></AuthLayout>;
}

function Sidebar({admin,logout}) {return <aside className="sidebar"><Logo/><nav><a className="active">{admin?'Applications':'Overview'}</a><a>{admin?'Students':'My programme'}</a><a>{admin?'Courses':'Assignments'}</a><a>{admin?'Announcements':'Resources'}</a></nav><button className="text-btn" onClick={logout}>Log out</button></aside>}

function StudentDashboard({user,logout}) {return <main className="dashboard"><Sidebar logout={logout}/><section className="dash-main"><div className="dash-title"><div><p className="eyebrow">DevOps student portal</p><h1>Welcome, {user.fullName.split(' ')[0]}.</h1></div><span className="avatar">{user.fullName[0]}</span></div><div className="notice"><strong>✓ Your account is approved</strong><p>You now have access to the Livingworth Academy DevOps learning portal.</p></div><div className="dash-grid"><article><span>Current programme</span><h3>12-Week DevOps Bootcamp</h3><p>Linux, Git, AWS, IaC, containers, Kubernetes, CI/CD and monitoring.</p></article><article><span>Weekly schedule</span><h3>Mon · Wed · Fri</h3><p>Live on Google Meet, 8:00–9:00 p.m. GMT+1.</p></article><article><span>Completion path</span><h3>Assignments + Capstone</h3><p>Maintain GitHub evidence and complete the final end-to-end project.</p></article></div><section className="portal-path"><p className="eyebrow">Your learning path</p><div>{['DevOps & SDLC','Linux & Bash','Git & GitHub','AWS','Ansible','Terraform','Docker','Kubernetes','CI/CD','Monitoring','Capstone'].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></section></section></main>}

function AdminDashboard({user,logout}) {
  const savedDemo=()=>JSON.parse(localStorage.getItem('lw_demo_students')||'null')||demoStudents;
  const [students,setStudents]=useState(user.demo?savedDemo():[]);const [message,setMessage]=useState(user.demo?'Offline preview: changes are stored only in this browser.':'');
  const load=()=>user.demo?setStudents(savedDemo()):api('/admin/students').then(setStudents).catch(e=>setMessage(e.message));useEffect(load,[]);
  async function decide(id,status){if(user.demo){const next=students.map(s=>s.id===id?{...s,status}:s);setStudents(next);localStorage.setItem('lw_demo_students',JSON.stringify(next));setMessage(`Demo student ${status}. This change is local only.`);return}try{const data=await api(`/admin/students/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});setMessage(data.message);load()}catch(e){setMessage(e.message)}}
  return <main className="dashboard"><Sidebar admin logout={logout}/><section className="dash-main"><div className="dash-title"><div><p className="eyebrow">Administrator portal {user.demo&&'· Offline preview'}</p><h1>Student applications</h1><p>Review registrations and control academy access.</p></div><span className="avatar">{user.fullName[0]}</span></div>{user.demo&&<div className="demo-banner"><b>Offline demo mode</b><span>These sample records and approvals exist only in this browser.</span></div>}<div className="metrics"><article><span>Pending</span><strong>{students.filter(s=>s.status==='pending').length}</strong></article><article><span>Approved</span><strong>{students.filter(s=>s.status==='approved').length}</strong></article><article><span>Total applications</span><strong>{students.length}</strong></article></div><p className="form-message success">{message}</p><div className="student-list">{students.length===0?<div className="empty">No student applications yet.</div>:students.map(s=><article key={s.id}><span className="student-avatar">{s.fullName[0]}</span><div className="student-info"><h3>{s.fullName}</h3><p>{s.email} · {s.phone||'No phone'}</p><small>{s.experienceLevel} — {s.learningGoal}</small></div><b className={`status ${s.status}`}>{s.status}</b>{s.status==='pending'&&<div className="review"><button onClick={()=>decide(s.id,'approved')}>Approve</button><button onClick={()=>decide(s.id,'rejected')}>Reject</button></div>}</article>)}</div></section></main>}

export default function App(){const[page,setPage]=useState('home');const[user,setUser]=useState(null);const[loading,setLoading]=useState(true);const navigate=p=>{setPage(p);scrollTo(0,0)};const logout=()=>{localStorage.removeItem('lw_token');localStorage.removeItem('lw_demo_admin');setUser(null);setPage('home')};useEffect(()=>{if(localStorage.getItem('lw_demo_admin')){setUser({id:'demo-admin',fullName:'Livingworth Administrator',email:'admin@livingworthacademy.com',role:'admin',status:'approved',demo:true});setPage('dashboard');setLoading(false);return}const token=localStorage.getItem('lw_token');if(token)api('/auth/me').then(u=>{setUser(u);setPage('dashboard')}).catch(()=>localStorage.removeItem('lw_token')).finally(()=>setLoading(false));else setLoading(false)},[]);if(loading)return <div className="loading">Loading Livingworth Academy…</div>;if(page==='register')return <Register navigate={navigate}/>;if(page==='student-login')return <Login portal="student" navigate={navigate} onLogin={u=>{setUser(u);setPage('dashboard')}}/>;if(page==='admin-login')return <Login portal="admin" navigate={navigate} onLogin={u=>{setUser(u);setPage('dashboard')}}/>;if(page==='dashboard'&&user)return user.role==='admin'?<AdminDashboard user={user} logout={logout}/>:<StudentDashboard user={user} logout={logout}/>;return <Home navigate={navigate}/>}
