import { useEffect, useState, type ReactNode } from 'react';

const icons: Record<string,string> = { Overview:'⌂',Applications:'◫',Students:'◉',Certificates:'◇',Leaderboard:'↗',Mentors:'♙',Stories:'✦','My stories':'✦',Announcements:'◌',Programme:'▦',Learning:'▤',Assignments:'✓',Attendance:'◷','Live class':'●','Live quiz':'⚡',Notifications:'◎',Security:'⌾' };

export default function PortalShell({ role,user,active,items,onSelect,logout,children,unreadAnnouncements=0,forceSecurity=false }: { role:string; user:any; active:string; items:string[]; onSelect:(item:string)=>void; logout:()=>void; children:ReactNode; unreadAnnouncements?:number; forceSecurity?:boolean }) {
  const [open,setOpen]=useState(false); const [assignmentCount,setAssignmentCount]=useState(0);
  useEffect(()=>{ if(forceSecurity||localStorage.getItem('lw_demo_admin'))return; let live=true; const refresh=async()=>{try{const res=await fetch('/api/assignments/pending-count',{headers:{Authorization:`Bearer ${localStorage.getItem('lw_token')}`}});if(res.ok&&live)setAssignmentCount((await res.json()).count||0)}catch{}};refresh();const timer=setInterval(refresh,30000);window.addEventListener('lw-assignments-changed',refresh);return()=>{live=false;clearInterval(timer);window.removeEventListener('lw-assignments-changed',refresh)}},[role,active,forceSecurity]);
  const visible=forceSecurity?['Security']:items;
  return <div className="learning-app">
    <header className="learning-topbar"><a className="learning-logo" href="/"><img src="/livingworth-logo.jpeg" alt="Livingworth Academy"/></a><div className="learning-search"><span>⌕</span><input aria-label="Search portal" placeholder="Search your academy" disabled/><kbd>⌘ K</kbd></div><div className="learning-user"><button className="learning-mobile" onClick={()=>setOpen(!open)} aria-label="Open menu">☰</button><span>{user.fullName?.[0]}</span><div><strong>{user.fullName}</strong><small>{role}</small></div></div></header>
    <aside className={`learning-rail ${open?'open':''}`}><div className="rail-label">Workspace</div><nav>{visible.map(item=><button key={item} className={active===item?'active':''} onClick={()=>{onSelect(item);setOpen(false)}}><i>{icons[item]||'·'}</i><span>{item}</span>{item==='Announcements'&&unreadAnnouncements>0&&<b>{unreadAnnouncements}</b>}{item==='Assignments'&&assignmentCount>0&&<b>{assignmentCount}</b>}</button>)}</nav><div className="rail-help"><span>Need help?</span><p>Reach out to your mentor whenever you feel stuck.</p></div><button className="rail-logout" onClick={logout}>↪ <span>Log out</span></button></aside>
    <main className="learning-workspace"><header className="workspace-heading"><div><span>{role} workspace</span><h1>{active==='Overview'?`Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, ${user.fullName?.split(' ')[0]}.`:active}</h1><p>{active==='Overview'?'Here is what is happening across your Livingworth journey today.':'Your dedicated space for everything related to this area.'}</p></div><div className="workspace-date"><small>Today</small><strong>{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</strong></div></header><div className="workspace-content">{children}</div></main>
  </div>;
}
